language: python
python:
  - 2.7
install:
  - python setup.py install
  - pip install coveralls
  - pip install pytest-cov
script:
  - pylint --rcfile=.pylintrc sophon
  - pylint --rcfile=.pylintrc tests
  - py.test --cov=sophon tests/
after_success:
  - coveralls
